plugins {
    id 'io.micronaut.build.internal.test-application'
}

dependencies {
    implementation projects.micronautJdbcUcp
    implementation projects.micronautTests.micronautCommonSync

    runtimeOnly libs.managed.ojdbc17
    runtimeOnly libs.managed.ucp17

    testImplementation projects.micronautTests.micronautCommonTests
    testImplementation(mnData.micronaut.data.tx.jdbc)
}

micronaut {
    testResources {
        additionalModules.add("jdbc-oracle-free")
    }
}
