plugins {
    id 'io.micronaut.build.internal.bom'
}

micronautBom {
    excludeProject.set({ p ->
        p.path.startsWith(':test')
    } as Spec<Project>)
}

micronautBom {
    suppressions {
        acceptedLibraryRegressions.add("micronaut-hibernate-jpa-spring")
        acceptedLibraryRegressions.add("micronaut-jdbc-unpooled")
        acceptedVersionRegressions.add("commons-dbcp-compat")
        acceptedLibraryRegressions.add("commons-dbcp")
        acceptedVersionRegressions.add("ojdbcdms")
        acceptedLibraryRegressions.add("ojdbc8")
        acceptedLibraryRegressions.add("ucp")
    }
}
