All of the implementation specific parameters can be configured. Effort was made to allow basic configuration to be consistent across the implementations.

If you want Micronaut to avoid connection pooling entirely, add the `micronaut-jdbc-unpooled` module instead. It uses the same common datasource settings, creates a new physical JDBC connection for each `getConnection()` call, and closes that physical connection when the caller closes it.

* Hikari: The URL is able to be configured through `url` in addition to `jdbcUrl`. The JNDI name can be configured through `jndiName` in addition to `dataSourceJNDI`.
* Tomcat: The JNDI name can be configured through `jndiName` in addition to `dataSourceJNDI`.

Several configuration options will be calculated if they are not provided.

[cols="20%,80%"]
|=======
|URL |The classpath will be searched for an embedded database driver. If found, the URL will be set to the default value for that driver.
|Driver Class|If the URL is configured, the driver class will be derived from the URL, otherwise the classpath will be searched for an embedded database driver. If found, the default class name for that driver will be used.
|Username |If the configured database driver is embedded, the username will be set to "sa"
|Password |If the configured database driver is embedded, the password will be set to an empty string.
|=======

For example:

[configuration]
----
datasources.default: {}
----

The above configuration will result in a single link:{jdkapi}/java.sql/javax/sql/DataSource.html[DataSource] bean being registered with the named qualifier of `default`.

If for example, the H2 driver is on the classpath, it is equivalent to the following:

[configuration]
----
datasources:
    default:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ""
        driverClassName: org.h2.Driver
----

To use Oracle UCP, provide a configuration similar to the following:

[configuration]
----
datasources:
  default:
    url:
    connectionFactoryClassName: oracle.jdbc.pool.OracleDataSource
    username:
    password:
    minPoolSize: 1
    maxPoolSize: 10
----

The Oracle UCP is managed by the link:https://docs.oracle.com/en/database/oracle/oracle-database/21/jjuar/oracle/ucp/admin/UniversalConnectionPoolManager.html[UniversalConnectionPoolManager]. The manager can be disabled byt setting `ucp-manager.enabled` to `false`. Additionally, you can enable the link:https://docs.oracle.com/en/database/oracle/oracle-database/21/jjucp/jmx-based-management.html[JMX-Based Management] by setting the `ucp-manager.jmx.enabled` to `true` and providing the `ojdbc8dms.jar` and `dms.jar` dependencies.

In case when exception `Universal Connection Pool already exists in the Universal Connection Pool Manager` is thrown, there is `oracle.ucp.destroyOnReload` configuration that can be set to `true` to avoid this error. In that case, when creating new connection pool, if there is the one with the same name the old one will be destroyed first.

There is also property `oracle.ucp.createConnectionInBorrowThread` that can control connection creation using background threads. The default configuration since UCP 23.x is that connections are created using background threads instead of user threads.
Adding configuration `oracle.ucp.createConnectionInBorrowThread=true` will switch to the old behavior.
More about it can be read here link:https://docs.oracle.com/en/database/oracle/oracle-database/23/jjucp/borrowing-ucp-connections.html[Borrowing Connections from UCP].

For a list of other properties able to be configured, simply refer to the implementation that is being used. All setter methods are candidates for configuration.

|=======
|Connection Pool |Javadoc |Configuration |Pool Documentation

|Tomcat
|link:https://tomcat.apache.org/tomcat-9.0-doc/api/org/apache/tomcat/jdbc/pool/PoolProperties.html[PoolProperties]
|https://micronaut-projects.github.io/micronaut-sql/latest/guide/configurationreference.html#io.micronaut.configuration.jdbc.tomcat.DatasourceConfiguration[DatasourceConfiguration]
|https://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html[Tomcat Connection Pool]

|Hikari
|link:http://static.javadoc.io/com.zaxxer/HikariCP/2.7.1/com/zaxxer/hikari/HikariConfig.html[HikariConfig]
|https://micronaut-projects.github.io/micronaut-sql/latest/guide/configurationreference.html#io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration[DatasourceConfiguration]
|https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#gear-configuration-knobs-baby[Hikari Docs]

|Apache DBCP
|link:http://commons.apache.org/proper/commons-dbcp/api-2.1.1/org/apache/commons/dbcp2/BasicDataSource.html[BasicDataSource]
|https://micronaut-projects.github.io/micronaut-sql/latest/guide/configurationreference.html#io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration[DatasourceConfiguration]
|https://commons.apache.org/proper/commons-dbcp/configuration.html[Apache DBCP Configuration]


|Oracle UCP
|link:https://docs.oracle.com/en/database/oracle/oracle-database/21/jjuar/oracle/ucp/jdbc/PoolDataSource.html[PoolDataSource]
|https://micronaut-projects.github.io/micronaut-sql/latest/guide/configurationreference.html#io.micronaut.configuration.jdbc.ucp.DatasourceConfiguration[DatasourceConfiguration]
|https://docs.oracle.com/en/database/oracle/oracle-database/21/jjucp/intro.html#GUID-197BA5D3-86DA-43BE-AFC6-E8CBED4883EF[Oracle UCP]

|=======

=== Oracle Session Program Auto-Configuration

Micronaut SQL can automatically set the Oracle `v$session.program` connection property so your application's sessions are easily identifiable in Oracle tools (such as `v$session`).

- Applied only to Oracle datasources (when `dialect: ORACLE` is set or the JDBC URL starts with `jdbc:oracle`).
- The value is taken from `micronaut.application.name`.
- Does not override a user-provided `v$session.program`.
- Supported for HikariCP, Tomcat JDBC, Apache DBCP2, and Oracle UCP.
- Scope limited to `v$session.program` only (it does not set ClientId/Module/Action).

Configure per datasource:

[configuration]
----
micronaut:
  application:
    name: my-app

datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: user
    password: pass
    dialect: ORACLE

  other:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: user
    password: pass
    dialect: ORACLE
    oracle:
      session:
        enabled: false
----
<1> The `default` data source auto-sets v$session.program = "my-app"
<2> The `other` data source v$session.program not auto-set because `datasources.other.oracle.session.enabled` is set to `false`

Alternatively, this configuration will set "My Program" as session name for the Oracle connection and Micronaut
will not try to use application name for it:

[configuration]
----
micronaut:
  application:
    name: my-app
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: user
    password: pass
    dialect: ORACLE
    data-source-properties:
      v$session.program: "My Program"
----
