Java data sources can be configured for one of five currently provided implementations. Apache DBCP2, Hikari, Tomcat, Oracle Universal Connection Pool, and an unpooled DriverManager-backed datasource are supported by default.

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply one of the `jdbc-tomcat`, `jdbc-hikari`, `jdbc-dbcp`, or `jdbc-ucp` features to preconfigure a simple JDBC connection in your project, along with a default H2 database driver:
----
$ mn create-app my-app --features jdbc-tomcat
----
====

To get started, simply add a dependency to one of the JDBC configurations that corresponds to the implementation you would like to use. Choose one of the following:

dependency:micronaut-jdbc-tomcat[groupId="io.micronaut.sql", scope="runtime"]

dependency:micronaut-jdbc-hikari[groupId="io.micronaut.sql", scope="runtime"]

dependency:micronaut-jdbc-dbcp[groupId="io.micronaut.sql", scope="runtime"]

dependency:micronaut-jdbc-ucp[groupId="io.micronaut.sql", scope="runtime"]

dependency:micronaut-jdbc-unpooled[groupId="io.micronaut.sql", scope="runtime"]

You also need to add a JDBC driver dependency to your classpath. For example to add the http://www.h2database.com[H2 In-Memory Database]:

dependency:h2[groupId="com.h2database", scope="runtime"]

To use SQLite, add the Xerial JDBC driver:

dependency:sqlite-jdbc[groupId="org.xerial", scope="runtime"]

When the SQLite driver is present, Micronaut can automatically configure an embedded shared in-memory datasource for `db-type: sqlite` if you do not provide an explicit JDBC URL.
