Micronaut supports automatically configuring https://mybatis.org/mybatis-3/[MyBatis] for SQL mappers built on top of JDBC.

To configure MyBatis you should first add the `mybatis` module to your classpath:

dependency:micronaut-mybatis[groupId="io.micronaut.sql"]

MyBatis support builds on Micronaut JDBC. In addition to `micronaut-mybatis`, add one of the <<jdbc, JDBC runtime modules>> and a JDBC driver dependency.

Once those dependencies are present, <<jdbc, configure one or many DataSources>>. For example:

[configuration]
----
datasources:
  default:
    url: jdbc:h2:mem:devDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
----

For each registered `DataSource`, Micronaut will configure the following MyBatis beans using api:configuration.mybatis.MyBatisFactory[]:

* link:https://mybatis.org/mybatis-3/apidocs/org/apache/ibatis/session/Configuration.html[Configuration] - the MyBatis `Configuration`
* link:https://mybatis.org/mybatis-3/apidocs/org/apache/ibatis/session/SqlSessionFactory.html[SqlSessionFactory] - the MyBatis session factory
* link:https://mybatis.org/mybatis-3/apidocs/org/apache/ibatis/session/SqlSessionManager.html[SqlSessionManager] - a thread-safe session manager

If no MyBatis transaction factory is provided for a `DataSource`, Micronaut uses link:https://mybatis.org/mybatis-3/apidocs/org/apache/ibatis/transaction/jdbc/JdbcTransactionFactory.html[JdbcTransactionFactory].

When multiple datasources are configured, Micronaut qualifies each MyBatis bean with the datasource name. You can then inject the `Configuration`, `SqlSessionFactory`, or `SqlSessionManager` for a specific datasource with `@Named`.

Mapper interfaces are not registered automatically. You can register mappers and apply additional configuration through <<mybatis-customizers,customizer beans>>, then obtain them from the corresponding `SqlSessionManager`.

For a complete application example, see the https://guides.micronaut.io/latest/micronaut-data-access-mybatis.html[Micronaut Data access MyBatis guide].
