Micronaut supports reactive and non-blocking client to connect to MySQL using https://github.com/eclipse-vertx/vertx-sql-client[vertx-mysql-client], allowing  to handle many database connections with a single thread.

== Configuring the MySQL Vertx Client
[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `vertx-mysql-client` feature to configure the MySQL Vertx client in your project:
----
$ mn create-app my-app --features vertx-mysql-client
----
====

To configure the MySQL Vertx client you should first add `vertx-mysql-client` module to your classpath:

dependency:micronaut-vertx-mysql-client[groupId="io.micronaut.configuration"]

You should then configure the URI or https://vertx.io/docs/vertx-mysql-client/java/[`MySQLConnectOptions`,`PoolOptions`] of the MySQL server you wish to communicate with in `application.yml`:

[source,yaml]
.application.yml
----
vertx:
	mysql:
	    client:
            port: 3306
            host: the-host
            database: the-db
            user: test
            password: test
        pool:
            maxSize: 5
----

TIP: You can also connect to MySQL using `uri` instead of the other properties.

Once you have the above configuration in place then you can inject the `io.vertx.reactivex.mysqlclient.MySQLPool` bean. The following is the simplest way to connect:

[source,groovy]
----
include::vertx-mysql-client/src/test/groovy/io/micronaut/configuration/vertx/mysql/client/MySQLClientSpec.groovy[tags=query,indent=0]
----

<1> `client` is an instance of the `io.vertx.reactivex.mysqlclient.MySQLPool` bean.

For more information on running queries on MySQL using the reactive client please read the "Running queries" section in the documentation of https://vertx.io/docs/vertx-mysql-client/java/[vertx-mysql-client].

== MySQL Health Checks

When the `vertx-mysql-client` module is activated a api:configuration.vertx.mysql.client.health.MySQLClientPoolHealthIndicator[] is activated resulting in the `/health` endpoint and api:health.CurrentHealthStatus[] interface resolving the health of the MySQL connection.

The only configuration option supported is to enable or disable the indicator by the `endpoints.health.vertx.mysql.client.enabled` key.

See the section on the <https://docs.micronaut.io/latest/guide/index.html#healthEndpoint[Health Endpoint] for more information.