Micronaut supports reactive and non-blocking client to connect to Postgres using https://github.com/eclipse-vertx/vertx-sql-client[vertx-pg-client], allowing  to handle many database connections with a single thread.

== Configuring the Pg Vertx Client
[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `vertx-pg-client` feature to configure the Postgres Vertx client in your project:
----
$ mn create-app my-app --features vertx-pg-client
----
====

To configure the Postgres Vertx client you should first add `vertx-pg-client` module to your classpath:

dependency:micronaut-vertx-pg-client[groupId="io.micronaut.configuration"]

You should then configure the URI or https://vertx.io/docs/vertx-pg-client/java/[`PgConnectOptions`,`PoolOptions`] of the Postgres server you wish to communicate with in `application.yml`:

[source,yaml]
.application.yml
----
vertx:
	pg:
	    client:
            port: 3306
            host: the-host
            database: the-db
            user: test
            password: test
            maxSize: 5
----

TIP: You can also connect to Postgres using `uri` instead of the other properties.

Once you have the above configuration in place then you can inject the `io.vertx.reactivex.pgclient.PgPool` bean. The following is the simplest way to connect:

[source,groovy]
----
include::vertx-pg-client/src/test/groovy/io/micronaut/configuration/vertx/pg/client/PgClientSpec.groovy[tags=query,indent=0]
----

<1> `client` is an instance of the `io.vertx.reactivex.pgclient.PgPool` bean.

For more information on running queries on Postgres using the reactive client please read the "Running queries" section in the documentation of https://vertx.io/docs/vertx-pg-client/java/[vertx-pg-client].

== Postgres Health Checks

When the `vertx-pg-client` module is activated a api:configuration.vertx.pg.client.health.PgClientPoolHealthIndicator[] is activated resulting in the `/health` endpoint and api:health.CurrentHealthStatus[] interface resolving the health of the Postgres connection.

The only configuration option supported is to enable or disable the indicator by the `endpoints.health.vertx.pg.client.enabled` key.

See the section on the <https://docs.micronaut.io/latest/guide/index.html#healthEndpoint[Health Endpoint] for more information.