plugins {
    id "io.micronaut.build.internal.parent"
}

repositories {
    mavenCentral()
}

if (System.getenv("SONAR_TOKEN") != null) {
    sonarqube {
        properties {
            property "sonar.exclusions", "**/example/**"
        }
    }
}

// TODO: Workaround for duplicated doc file
// Entry io.vertx.sqlclient.PoolOptions.adoc is a duplicate
tasks.named("processConfigProps") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
