pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.0-M17'
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

micronautBuild {
    useStandardizedProjectNames = true
    importMicronautCatalog()
    importMicronautCatalog("micronaut-cache")
    importMicronautCatalog("micronaut-data")
    importMicronautCatalog("micronaut-micrometer")
    importMicronautCatalog("micronaut-reactor")
    importMicronautCatalog("micronaut-r2dbc")
    importMicronautCatalog("micronaut-serde")
    importMicronautCatalog("micronaut-spring")
    importMicronautCatalog("micronaut-test-resources")
    importMicronautCatalog("micronaut-validation")
}

rootProject.name = 'sql-parent'

include 'sql-bom'
include 'jdbc'
include 'jdbc-dbcp'
include 'jdbc-hikari'
include 'jdbc-tomcat'
include 'jdbc-unpooled'
include 'jdbc-ucp'
include 'jasync-sql'
include 'hibernate-jpa'

include 'hibernate-reactive'
include 'jooq'

include 'vertx-mysql-client'
include 'vertx-pg-client'
include 'jdbi'

include 'tests:common'
include 'tests:common-reactive'
include 'tests:common-sync'
include 'tests:common-tests'

include 'tests:hibernate:hibernate-sync-common'
include 'tests:hibernate:hibernate-h2'
include 'tests:hibernate:hibernate-mariadb'
include 'tests:hibernate:hibernate-mysql'
include 'tests:hibernate:hibernate-mysql-disabled'
include 'tests:hibernate:hibernate-mssql'
include 'tests:hibernate:hibernate-oracle'
include 'tests:hibernate:hibernate-postgres'

include 'tests:hibernate:hibernate-reactive-common'
include 'tests:hibernate:hibernate-reactive-mssql'
include 'tests:hibernate:hibernate-reactive-mysql'
include 'tests:hibernate:hibernate-reactive-oracle'
include 'tests:hibernate:hibernate-reactive-postgres'

include 'tests:jooq-tests:jooq-jdbc-postgres'
include 'tests:jooq-tests:jooq-r2dbc-postgres'
include 'tests:vertx-pg-client-native'

include 'tests:jdbc-ucp-tests:jdbc-ucp-oracle'
include 'tests:jdbc-dbcp-tests:jdbc-dbcp-postgres'
include 'tests:jdbc-hikari-tests:jdbc-hikari-h2'
include 'tests:jdbc-hikari-tests:jdbc-hikari-sqlite'
include 'tests:jdbc-tomcat-tests:jdbc-tomcat-mysql'
