plugins {
    id 'io.micronaut.build.internal.sql-module'
}

micronautBuild {
    binaryCompatibility {
        enabledAfter("7.0.0")
    }
}

dependencies {
    api projects.micronautJdbc
    api(mn.micronaut.context)
    api(mn.micronaut.inject)
    api(libs.managed.mybatis)

    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mnTest.micronaut.test.junit5)

    testRuntimeOnly projects.micronautJdbcHikari
    testRuntimeOnly(libs.managed.h2)
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
    testRuntimeOnly(mnTest.junit.platform.launcher)
}

tasks.named("test", Test) {
    useJUnitPlatform()
}
