plugins {
    id("io.micronaut.build.internal.test-application-hibernate")
}

dependencies {
    implementation projects.micronautTests.micronautHibernate.micronautHibernateSyncCommon
    testImplementation projects.micronautTests.micronautCommonTests

    runtimeOnly projects.micronautJdbcTomcat

    runtimeOnly libs.managed.ojdbc11
}

configurations {
    all*.exclude module: "javassist"
}

micronaut {
    testResources {
        additionalModules.add("jdbc-oracle-free")
    }
}
