plugins {
    id 'io.micronaut.build.internal.sql-module'
}

dependencies {
    annotationProcessor(mn.micronaut.graal)

    api(projects.micronautHibernateJpa) {
        exclude module: 'jdbc'
        exclude group: 'micronaut-data'
    }
    api (libs.managed.hibernate.reactive.core) {
        // TODO: Temp exclude since hibernate-reactive brings in vert-sql-client 4.5.22
        // which has vulnerability and we will use 4.5.24 override from the catalog
        exclude group: 'io.vertx', module: 'vertx-sql-client'
    }
    api mn.micronaut.runtime

    compileOnly libs.managed.vertx.sql.client
    runtimeOnly libs.managed.ongres.scram.client

    testAnnotationProcessor mn.micronaut.inject.java
    testImplementation mn.micronaut.inject.java
    testImplementation mn.micronaut.inject.groovy
    testImplementation projects.micronautJdbc
    testRuntimeOnly projects.micronautJdbcTomcat
    testRuntimeOnly(libs.managed.h2)

    testImplementation(mnTestResources.testcontainers.jdbc)
    testImplementation(mnTestResources.testcontainers.postgres)
    testImplementation libs.managed.vertx.pg.client
    testImplementation(mnData.micronaut.data.tx.hibernate)
}
