/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.configuration.mybatis;

import org.apache.ibatis.io.ResolverUtil;
import org.apache.ibatis.session.Configuration;

/**
 * Registers mapper interfaces with the MyBatis {@link Configuration} of a datasource.
 *
 * <p>Implementations are generated by the {@code micronaut-mybatis-processor} for every
 * {@link MyBatisMapperScan} and discovered through {@code META-INF/services}. They are applied
 * by {@link MyBatisFactory} after all {@link MyBatisConfigurationCustomizer} beans.</p>
 *
 * @since 7.2.0
 */
public interface MyBatisMapperScanRegistration {

    /**
     * @return The name of the datasource whose configuration receives the mappers
     */
    String getDatasourceName();

    /**
     * Registers the mapper interfaces.
     *
     * @param configuration The MyBatis configuration
     */
    void register(Configuration configuration);

    /**
     * Adds a mapper interface unless it is already known to the configuration.
     *
     * @param configuration The MyBatis configuration
     * @param mapperType    The mapper interface
     */
    default void addMapper(Configuration configuration, Class<?> mapperType) {
        if (!configuration.hasMapper(mapperType)) {
            configuration.addMapper(mapperType);
        }
    }

    /**
     * Adds all mapper interfaces of a package using MyBatis runtime scanning. This is the JVM fallback
     * for packages in which the annotation processor could not discover any mapper interface. Unlike
     * {@link Configuration#addMappers(String)}, interfaces already known to the configuration (for example
     * because they are also listed explicitly) are skipped.
     *
     * @param configuration The MyBatis configuration
     * @param packageName   The package name
     */
    default void addMappers(Configuration configuration, String packageName) {
        ResolverUtil<Object> resolverUtil = new ResolverUtil<>();
        resolverUtil.find(new ResolverUtil.IsA(Object.class), packageName);
        for (Class<?> mapperType : resolverUtil.getClasses()) {
            if (mapperType.isInterface()) {
                addMapper(configuration, mapperType);
            }
        }
    }
}
