plugins {
    id 'io.micronaut.build.internal.test-application'
}

dependencies {
    implementation projects.micronautJdbcDbcp
    implementation projects.micronautTests.micronautCommonSync

    runtimeOnly libs.managed.postgresql
    // credentials refresh test runs against an in-memory database, without test resources
    testRuntimeOnly libs.managed.h2

    testImplementation projects.micronautTests.micronautCommonTests
    testImplementation(mnData.micronaut.data.tx.jdbc)
}

micronaut {
    testResources {
        additionalModules.add(JDBC_POSTGRESQL)
    }
}
