plugins {
    id 'io.micronaut.build.internal.sql-module'
}

dependencies {
    api(mn.micronaut.inject)
    api(libs.managed.vertx.pg.client)

    implementation(libs.managed.vertx.codegen)
    implementation(mnReactor.micronaut.reactor)

    compileOnly(libs.managed.vertx.rx.java3)

    compileOnly(mn.micronaut.management)
    runtimeOnly libs.managed.ongres.scram.client

    testImplementation(mn.micronaut.management)
    testImplementation(libs.managed.vertx.rx.java3)
    testImplementation(mnTestResources.testcontainers.postgres)
}
