plugins {
    id 'io.micronaut.build.internal.sql-test-suite'
    id 'groovy'
}

dependencies {
    testCompileOnly mn.micronaut.inject.groovy
    // maps jakarta.transaction.Transactional to Micronaut's transactional advice
    testCompileOnly mnData.micronaut.data.processor
    testImplementation mnTest.micronaut.test.spock
}
